config/routes.rb
Rails.application.routes.draw do
  devise_for :c_users, controllers:{
    sessions:       'c_users/sessions',
    passwords:      'c_users/passwords',
    registrations:  'c_users/registrations'
  }
  devise_for :users, controllers:{
    sessions:       'users/sessions',
    passwords:      'users/passwords',
    registrations:   'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root "informations#index"
  resources :mypage do
    collection do
      get "search"
    end
    collection do
      get "match"
    end
    collection do
      get "follow"
    end
    collection do
      get "find"
    end
    collection do
      get "community"
    end
    collection do
      post "create_follow"
    end 
    collection do
      post "destroy_follow"
    end
    collection do
      get "follower"
    end
    collection do
      get "match_approval"
    end
    collection do
      post "approve_match"
    end
    collection do
      post "destroy_match"
    end
    collection do
      get "show_message"
    end
    collection do
      post "create_message"
    end
    collection do
      get "show_user_message"
    end
    collection do
      get "skyway"
    end
    collection do
      get "create_skyway"
    end
    collection do
      get "show_c_detail"
    end
    collection do
      post "end_call"
    end
    collection do
      get "profile"
    end
    collection do
      post "update_profile"
    end
    collection do 
      post "add_main_image"
    end
    collection do
      post "add_sub_image"
    end
    collection do 
      get "delete_image"
    end
    collection do 
      get "qualification"
    end
  end
  resources :cmypage do
    collection do
      get "follower"
    end
    collection do
      get "search"
    end
    collection do
      get "find"
    end
    collection do
      get "community"
    end
    collection do
      get "user"
    end
    collection do
      get "match"
    end
    collection do
      get "follow"
    end
    collection do
      post "create_match"
    end
    collection do
      get "match_approvement"
    end
    collection do
      get "select_match"
    end
    collection do
      get "show_user"
    end
    collection do
      get "get_user_id"
    end
    collection do
      get "confirm_match"
    end
    collection do
      post "destroy_follow"
    end
    collection do
      post "create_follow"
    end
    collection do
      post "create_message"
    end
    collection do
      get "show_message"
    end
    collection do
      get "show_user_message"
    end
    collection do
      get "skyway"
    end
    collection do
      get "create_skyway"
    end
    collection do
      get "show_detail"
    end
    collection do
      post "end_call"
    end
    collection do
      get "profile"
    end
    collection do
      post "update_profile"
    end
    collection do 
      post "add_main_image"
    end
    collection do
      post "add_sub_image"
    end
    collection do 
      get "delete_image"
    end
    collection do
      get "qualification"
    end
  end
  namespace :api do
    resources :messages do
      collection do
        get "index_1"
      end
      collection do
        get "index_2"
      end
      collection do
        get "index_c"
      end
    end
  end
  # resources :messages
  resources :groups do
    resources :messages
  end
  resources :informations, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/cmypage_controller.rb
class CmypageController < ApplicationController
  before_action :authenticate_c_user!
  # before_action :configure_permitted_parameters, if: :devise_controller?
  
  def profile
    @my_image = Image.find_by(user_id: current_c_user.id, bool: 2)
    @c_user = CUser.new
    @image = Image.new
    @c_user_info = CUser.find(current_c_user.id)
    all_images = Image.where(user_id: current_c_user.id, bool: [2, 3])
    
    @main_image = all_images.find_by(bool: 2)
    images = all_images.where(bool: 3)
    @sub_images =[]
    images.each do |image|
      @sub_images << image
    end
  end

  def update_profile
    c_user = CUser.find(current_user.id)
    if c_user.update(update_profile_params)
      redirect_to search_cmypage_index_path
    end
  end

  def add_main_image
    c_user_images = Image.where(user_id: current_c_user.id, bool: 2)
    c_user_image = c_user_images.first
    c_user_images.each do |image|
      if image != c_user_image
        image.destroy
      end
    end
    if c_user_image.present?
      if c_user_image.update!(add_image_params)
        redirect_to profile_cmypage_index_path
      end
    else
      image = Image.new(add_image_params)
      # image = Image.new(image: add_image_params, bool: 0, user_id: current_user.id)
      image.bool = 2
      if image.save!
        redirect_to profile_cmypage_index_path
      end
    end
  end

  def add_sub_image
    if Image.c_new_multiple_image(add_sub_image_params)
      redirect_to profile_cmypage_index_path
    end
  end

  def delete_image
    @image_id = params[:id].to_i
    image = Image.find(@image_id)
    @bool = image.bool
    if image.destroy!
      respond_to do |format|
        format.json
      end
    end
  end

  def follow
    @follow = Follow.new
    @my_image = Image.find_by(user_id: current_c_user.id, bool: 2)
    user_ids = []
    follows = Follow.where(c_user_id: current_c_user.id, bool: [1, 2])
    follows.each do |follow|
      if user_ids.include?(follow.user_id)

      else
        user_ids << follow.user_id
      end
    end
    @items = []
    user_ids.each do |user_id|
      user = User.find(user_id)
      image = Image.find_by(user_id: user_id, bool: 0)
      item = { user: user, image: image }
      @items << item
    end
  end

  def follower
    @my_image = Image.find_by(user_id: current_c_user.id, bool: 2)
    @follow = Follow.new
    user_ids = []
    follows = Follow.where(c_user_id: current_c_user.id, bool: [0, 1])
    follows.each do |follow|
      if user_ids.include?(follow.user_id)

      else
        user_ids << follow.user_id
      end
    end
    @items = []
    user_ids.each do |user_id|
      user = User.find(user_id)
      image = Image.find_by(user_id: user_id, bool: 0)
      item = { user: user, image: image}
      @items << item
    end
  end

  def create_follow
    follow_backs = Follow.where(follow_params).where(bool: [0, 1])
    follows = Follow.where(follow_params).where(bool: 2)
    if follow_backs.present?
      follow_backs.each do |follow|
        follow.destroy
      end
      @follow = current_c_user.follows.new(follow_bool_params)
    else
      if follows.present?
        follows.each do |follow|
          follow.destroy
        end
      end
      @follow = current_c_user.follows.new(follow_two_bool_params)
    end
    if @follow.save
      respond_to do |format|
        format.json
      end
    end
  end

  def destroy_follow
    follows = current_c_user.follows.where(destroy_follow_params)
    @follow = follows.first()
    my_follows = follows.where(bool: 2)
    each_other_follows = follows.where(bool: [0, 1])
    if my_follows.present?
      my_follows.each do |follow|
        follow.destroy
      end
    else
      if each_other_follows.present?
        each_other_follows.each do |follow|
          follow.destroy
        end
      end
      @follow = current_c_user.follows.create(destroy_follow_zero_bool_params)
    end
    respond_to do |format|
      format.json
    end
  end

  def search
    @element_per_page = 2
    @my_image = Image.find_by(user_id: current_c_user.id, bool: 2)
    @follow = Follow.new
    original_users = []
    @all_user_length = User.all.length
    @users = User.page(params[:page]).per(@element_per_page)
    @users.each do |user|
      if original_users.include?(user)
      else
        original_users << user
      end
      if original_users.length >= 16
        break
      end
    end
    @items = []
    original_users.each do |user|
      image = Image.find_by(user_id: user.id, bool: 0)
      item = { user: user, image: image}
      @items << item
    end
  end

  def find
    
  end

  def community
    
  end

  def user
    
  end

  def match
    @message = Message.new
    @my_image = Image.find_by(user_id: current_c_user.id, bool: 2)
    matches = current_c_user.matches.where(step: 1)
    @items = []
    matches.each do |match|
      match.users.each do |user|
        item = {}
        if @items.present?
          @items.each_with_index do |already_item, i|
            if already_item[:user].id != user.id && @items.length != i + 1

            elsif already_item[:user].id == user.id
              break
            elsif already_item[:user].id != user.id && @items.length == i + 1
              item[:user] = user
            end
          end
        else
          item[:user] = user
        end
        if item != {}
          @items << item
        end
      end
    end
    @items.each do |item|
      user = item[:user]
      image = Image.find_by(user_id: user.id, bool: 0)
      item[:image] = image
    end
  end

  def show_message
    matches = []
    c_matches = current_c_user.matches.where(step: 1)
    user_id = params[:user_id].to_i
    user = User.find(user_id)
    image = Image.find_by(user_id: user.id, bool: 0)
    @item = { user: user, image:image }
    c_matches.each do |match|
      match.match_users.each do |match_user|
        if match_user.user_id == user_id      
          m = Match.find(match.id)
          matches << m
        end
      end
    end
    @others_items = []
    matches.each do |match|
      match.match_users.each do |match_user|
        if match_user.user_id != user_id
          u = User.find(match_user.user_id)
          image = Image.find_by(user_id: u.id, bool: 0)
          item = { user: u, image: image }
          if @others_items.include?(item)
          else
            @others_items << item
          end
        end
      end
    end
    @messages = []
    send_messages = Message.where(match_c_user_id: current_c_user.id, user_id: user_id, bool: 2)
    get_messages = Message.where(match_c_user_id: current_c_user.id, user_id: user_id, bool: 0)
    send_messages.each do |message|
      @messages << message
    end
    get_messages.each do |message|
      @messages.each_with_index do |array_message, i|
        if message.id < array_message.id
          @messages.insert(i, message)
          break
        elsif message.id > array_message.id && @messages.length == i + 1
          @messages.append(message)
        end
      end
    end
  end

  def show_user_message
    user_id = params[:user_id]
    @messages = Message.where(user_id: user_id, match_c_user_id: current_c_user.id, bool: [0, 2])
    user = User.find(user_id)
    image = Image.find_by(user_id: user_id, bool: 0)
    @item = {user: user, image: image}
  end

  def create_message
    @message = Message.create(create_message_params)
  end

  def select_match
    @my_image = Image.find_by(user_id: current_c_user.id, bool: 2)
  end

  def create_match
    user_id_1 = params[:user_id_1]
    user_id_2 = params[:user_id_2]
    match = current_c_user.matches.create(step: 0, memo: params[:memo])
    match_user_1 = match.match_users.create(user_id: user_id_1, content: params[:content1], step: 0)
    match_user_2 = match.match_users.create(user_id: user_id_2, content: params[:content2], step: 0)
    redirect_to action: :confirm_match
  end

  def match_approvement
    @match_users = []
    @my_image = Image.find_by(user_id: current_c_user.id, bool: 2)
    matches = Match.where(c_user_id: current_c_user.id, step: 0)
    matches.each do |match|
      items = {}
      match.match_users.each_with_index do |match_user, i|
        user_id = match_user.user_id
        step = match_user.step
        user = User.find(user_id)
        if i == 0
          items[:user1] = user
          items[:step1] = step
          items[:image1] = Image.find_by(user_id: user.id, bool: 0)
        elsif i == 1
          items[:user2] = user
          items[:step2] = step
          items[:image2] = Image.find_by(user_id: user.id, bool: 0)
        end
      end
      memo = match.memo
      items[:memo] = memo

      if @match_users.include?(items)
      elsif items[:user1].present?
        @match_users << items
      end
    end
  end

  def confirm_match
    
  end

  def show_user
    @create_id = params[:create_id].to_s
    @items = []
    user_ids = []
    # @follows = current_c_user.follows.where(bool: 1)
    follows = current_c_user.follows.where(bool: 1).limit(32)
    i = 0
    follows.each do |follow|
      i += 1
      if i == 17
        break
      end
      if user_ids.include?(follow.user_id)
      else
        user_ids << follow.user_id
      end
    end
    user_ids.each do |user_id|
      item = {}
      item[:user] = User.find(user_id)
      item[:image] = Image.find_by(user_id: user_id, bool: 0)
      @items << item
    end
  end

  def get_user_id
    user_id = params[:user_id].to_i
    @select_id = params[:select_id].to_i
    @user = User.find(user_id)
    @image = Image.find_by(user_id: user_id, bool: 0)
  end

  def show_detail
    user_id = params[:user_id]
    @user = User.find(user_id)
    @image = Image.find_by(user_id: user_id, bool: 0)
    @sub_images = Image.where(user_id: user_id, bool: 1)
    @student_length = current_c_user.follows.where(bool: 1).length
    @follower_length = current_c_user.follows.where(bool: [0, 1]).length
  end

  def skyway

app/views/cmypage/li_render_list/_c_user_line_list.html.haml
%li.user_approval_list
  .leftBox
    .userBox
      .text
        会員様
        = match_user[:user1].nickname
      .image_link
        - if match_user[:image1].present?
          = image_tag(match_user[:image1].image_url, class: "image")
        - else
          = image_tag('member_photo_noimage_thumb.png', class: "image")
  .commentBox
    .top
      メモ：
    .content
      = safe_join(match_user[:memo].split("\n"), tag(:br))
  .centerBox
    .userBox
      .text
        会員様
        = match_user[:user2].nickname
      .image_link
        - if match_user[:image2].present?
          = image_tag(match_user[:image2].image_url, class: "image")
        - else
          = image_tag('member_photo_noimage_thumb.png', class: "image")
  .approvalBox
    
    .stepBox
      %h3.subtitle
        承認済み：
      .text
        - if match_user[:step1] == 1 then
          = match_user[:user1].nickname
        - elsif match_user[:step2] == 1
          = match_user[:user2].nickname
        - else
          いません


      
    -# = form_with(model: @match, url: update_match_mypage_index_path, remote: true, class: "match_form", id: "approve_form_#{i + 1}") do |form|

    -# = form_with(model: @follow, url: create_follow_mypage_index_path, remote: true, class: "follow_form", id: "follow_form_#{i + 1}") do |form|

app/views/cmypage/li_render_list/_c_user_list.html.haml
%li.listBox
  .imageBox
    .image_link{ id: user.id }
      - if image.present? && image.image_url.present?
        = image_tag image.image_url, class: "image"
      - else
        = image_tag "member_photo_noimage_thumb.png", class: "image"
  .bottomBox
    .nameBox
      = user.username
    .love_sustainableBox
      -# <i class="fas fa-heart"></i>\f004
      %i.fas.fa-heart
      -# 合計マッチング承認数
      = user.match_users.where(step: 1).length
    .followerBox
      -# <i class="fas fa-user-graduate"></i>
      %i.fas.fa-user-graduate
      -# 生徒数なら@matches.length * 2、フォロワーならFollows.where(c_user: current_c_user) == @followerに.lengthだが、今回はfollowerにしようと思う。
      = user.follows.where(bool: [1, 2]).length
      人
    .specialtyBox
      .text
        %i.fas.fa-star
        ひとこと
        %i.fas.fa-star
      - if user.comment != nil
        = user.comment.truncate(21)
    - follow_status = user.follows.find_by(c_user_id: current_c_user.id)
    - if follow_status.present?
      - if follow_status.bool == 2 then
        .followedBox{ id: "#{user.id}" }
          = form_with(model: @follow, url: destroy_follow_cmypage_index_path, remote: true, class: "c_follow_form", id: "follow_form_#{i + 1}") do |form|
            = form.hidden_field :user_id, value: user.id
            = form.hidden_field :c_user_id, value: current_c_user.id
            = form.submit "＋フォロー", class: "c_followedBtn"
      - elsif follow_status.bool == 1 then
        .followedBox{ id: "#{user.id}" }
          = form_with(model: @follow, url: destroy_follow_cmypage_index_path, remote: true, class: "c_follow_form", id: "follow_form_#{i + 1}") do |form|
            = form.hidden_field :user_id, value: user.id
            = form.hidden_field :c_user_id, value: current_c_user.id
            = form.submit "フォロバ", class: "c_followedBtn"
      - elsif follow_status.bool == 0 then
        .followBox{ id: "#{user.id}" }
          = form_with(model: @follow, url: create_follow_cmypage_index_path, remote: true, class: "c_follow_form", id: "follow_form_#{i + 1}") do |form|
            = form.hidden_field :user_id, value: user.id
            = form.hidden_field :c_user_id, value: current_c_user.id
            = form.submit "フォロバ", class: "c_followBtn"
    - else
      .followBox{ id: "#{user.id}" }
        = form_with(model: @follow, url: create_follow_cmypage_index_path, remote: true, class: "c_follow_form", id: "follow_form_#{i + 1}") do |form|
          = form.hidden_field :user_id, value: user.id
          = form.hidden_field :c_user_id, value: current_c_user.id
          = form.submit "＋フォロー", class: "c_followBtn"
      
        -# - c_user.follows.each do |follow|
        -#   - if follow.user_id == current_user.id
        -#     = form.submit "＋フォロバ", class: "followBtn"
        -#     - break
        

      -# .followBtn
      -#   ＋フォロー
        
        -# %input{c_user: c_user, type: "hidden", value: c_user.id, class: "c_follow_hidden"}
        -# %input{user: current_user, type: "hidden", value: current_user.id, class: "follow_hidden"}