config/routes.rb
Rails.application.routes.draw do
  devise_for :c_users, controllers:{
    sessions:       'c_users/sessions',
    passwords:      'c_users/passwords',
    registrations:  'c_users/registrations'
  }
  devise_for :users, controllers:{
    sessions:       'users/sessions',
    passwords:      'users/passwords',
    registrations:   'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root "informations#index"
  resources :mypage do
    collection do
      get "search"
    end
    collection do
      get "match"
    end
    collection do
      get "follow"
    end
    collection do
      get "find"
    end
    collection do
      get "community"
    end
    collection do
      post "create_follow"
    end 
    collection do
      post "destroy_follow"
    end
    collection do
      get "follower"
    end
    collection do
      get "match_approval"
    end
    collection do
      post "approve_match"
    end
    collection do
      post "destroy_match"
    end
    collection do
      get "show_message"
    end
    collection do
      post "create_message"
    end
    collection do
      get "show_user_message"
    end
    collection do
      get "skyway"
    end
    collection do
      get "create_skyway"
    end
    collection do
      get "show_c_detail"
    end
    collection do
      post "end_call"
    end
    collection do
      get "profile"
    end
    collection do
      post "update_profile"
    end
    collection do 
      post "add_main_image"
    end
    collection do
      post "add_sub_image"
    end
    collection do 
      get "delete_image"
    end
    collection do 
      get "qualification"
    end
  end
  resources :cmypage do
    collection do
      get "follower"
    end
    collection do
      get "search"
    end
    collection do
      get "find"
    end
    collection do
      get "community"
    end
    collection do
      get "user"
    end
    collection do
      get "match"
    end
    collection do
      get "follow"
    end
    collection do
      post "create_match"
    end
    collection do
      get "match_approvement"
    end
    collection do
      get "select_match"
    end
    collection do
      get "show_user"
    end
    collection do
      get "get_user_id"
    end
    collection do
      get "confirm_match"
    end
    collection do
      post "destroy_follow"
    end
    collection do
      post "create_follow"
    end
    collection do
      post "create_message"
    end
    collection do
      get "show_message"
    end
    collection do
      get "show_user_message"
    end
    collection do
      get "skyway"
    end
    collection do
      get "create_skyway"
    end
    collection do
      get "show_detail"
    end
    collection do
      post "end_call"
    end
    collection do
      get "profile"
    end
    collection do
      post "update_profile"
    end
    collection do 
      post "add_main_image"
    end
    collection do
      post "add_sub_image"
    end
    collection do 
      get "delete_image"
    end
    collection do
      get "qualification"
    end
  end
  namespace :api do
    resources :messages do
      collection do
        get "index_1"
      end
      collection do
        get "index_2"
      end
      collection do
        get "index_c"
      end
    end
  end
  # resources :messages
  resources :groups do
    resources :messages
  end
  resources :informations, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  before_action :authenticate_user!
  # before_action :configure_permitted_parameters, if: :devise_controller?
  
  def index
    
  end

  def find
    
  end

  def community
    
  end

  def follow
    @bool = "follow"
    @follow = Follow.new
    @my_image = Image.find_by(user_id: current_user.id, bool:0)
    c_users = []
    # フォロー中の人を取得
    user_follows = Follow.where(user_id: current_user.id, bool: [0, 1])
    user_follows.each do |user_follow|
      c_user_id = user_follow.c_user_id
      c_user = CUser.find(c_user_id)
      if c_users.include?(c_user)
      else
        c_users << c_user
      end
    end
    @items = []
    c_users.each do |c_user|
      image = Image.find_by(user_id: c_user.id, bool: 2)
      item = {image: image, c_user: c_user}
      @items << item
    end
  end

  def qualification
    down_age = params[:downage]
    up_age = params[:upage]
    sex = params[:sex]
    if sex == ""
      sex = [0, 1]
    end
    if down_age == ""
      down_age = "18"
    end
    if up_age == ""
      up_age = "100"
    end
    @element_per_page = 2
    @c_users = CUser.where(sex: sex, age: down_age..up_age).page(params[:page]).per(@element_per_page)
    @my_image = Image.find_by(user_id: current_user.id, bool:0)
    @follow = Follow.new
    @items = []
    @c_users.each do |c_user|
      image = Image.find_by(user_id: c_user.id, bool: 2)
      item = {image: image, c_user: c_user}
      @items << item
    end
  end

  def profile
    @my_image = Image.find_by(user_id: current_user.id, bool:0)
    @user = User.new
    @image = Image.new
    @user_info = User.find(current_user.id)
    all_images = Image.where(user_id: current_user.id)
    @main_image = all_images.find_by(bool: 0)
    images = all_images.where(bool: 1)
    @sub_images =[]
    images.each do |image|
      @sub_images << image
    end
  end

  def update_profile
    user = User.find(current_user.id)
    if user.update(update_profile_params)
      redirect_to search_mypage_index_path
    end
  end

  def add_main_image
    user_images = Image.where(user_id: current_user.id, bool: 0)
    user_image = user_images.first
    user_images.each do |image|
      if image != user_image
        image.destroy
      end
    end
    if user_image.present?
      if user_image.update!(add_image_params)
        redirect_to profile_mypage_index_path
      end
    else
      image = Image.new(add_image_params)
      # image = Image.new(image: add_image_params, bool: 0, user_id: current_user.id)
      image.bool = 0
      if image.save!
        redirect_to profile_mypage_index_path
      end
    end
  end

  def add_sub_image
    if Image.new_multiple_image(add_sub_image_params)
      redirect_to profile_mypage_index_path
    end
  end

  def delete_image
    @image_id = params[:id].to_i
    image = Image.find(@image_id)
    @bool = image.bool
    if image.destroy!
      respond_to do |format|
        format.json
      end
    end
  end

  def follower
    @bool = "follower"
    @follow = Follow.new
    c_users = []
    @my_image = Image.find_by(user_id: current_user.id, bool: 0)
    # フォロワーの取得
    user_followers = Follow.where(user_id: current_user.id, bool: [1, 2])
    user_followers.each do |user_follower|
      c_user_id = user_follower.c_user_id
      # @c_users << CUser.find(c_user_id)
      c_user = CUser.find(c_user_id)
      if c_users.include?(c_user)
      else
        c_users << c_user
      end
    end
    @items = []
    c_users.each do |c_user|
      image = Image.find_by(user_id: c_user.id, bool: 2)
      item = {image: image, c_user: c_user}
      @items << item
    end
  end

  def create_follow
    # binding.pry
    follow_backs = current_user.follows.where(follow_params).where(bool: [1, 2])
    follows = current_user.follows.where(follow_params).where(bool: 0)
    if follow_backs.present?
      follow_backs.each do |follow|
        follow.destroy
      end
      # @follow = current_user.follows.new(follow_bool_params)
      @follow = current_user.follows.new(follow_bool_params)
    else
      if follows.present?
        follows.each do |follow|
          follow.destroy
        end
      end
      @follow = current_user.follows.new(follow_zero_bool_params)
    end
    if @follow.save
      respond_to do |format|
        format.json
      end
      # redirect_to action: :search
    end
  end

  def destroy_follow
    @follows = Follow.where(destroy_follow_params)
    @follow = @follows.first()
    @follows.each do |follow|
      follow.destroy
      if follow.bool == 0
        follow.destroy
      elsif follow.bool == 1
        follow.destroy
        # binding.pry
        Follow.create(destroy_follow_two_bool_params)
        # binding.pry
      elsif follow.bool == 2
        # 相手フォロー時は何もしない
      else
        follow.destroy
      end
    end

    respond_to do |format|
      format.json
    end
  end

  def match
    @message = Message.new
    @my_image = Image.find_by(user_id: current_user.id, bool: 0)
    @matches_items = []
    matches = current_user.matches.where(step: 1)
    if matches.present?
      matches.each do |match|
        match_items = {}
        match_items[:c_user] = CUser.find(match.c_user_id)
        match.match_users.each do |match_user|
          if match_user.user_id != current_user.id
            match_items[:user] = User.find(match_user.user_id)
          end
        end
        @matches_items.each do |m_items|
          if m_items == match_items
            match_items.clear()
          end
        end
        if match_items.present?
          @matches_items << match_items
        end
      end
    end
    @matches_items.each do |matches_item|
      u_image = Image.find_by(user_id: matches_item[:user].id, bool: 0)
      c_image = Image.find_by(user_id: matches_item[:c_user].id, bool: 2)
      matches_item[:u_image] = u_image
      matches_item[:c_image] = c_image
    end
  end

  def match_approval
    @match = Match.new
    @my_image = Image.find_by(user_id: current_user.id, bool: 0)
    @matches = []
    matches = current_user.matches.where(step: 0)
    matches.each do |match|
      matches_users = {}
      match.match_users.each do |match_user|
        if match_user.user_id != current_user.id
          matches_users[:user] = User.find(match_user.user_id)
          matches_users[:image] = Image.find_by(user_id: matches_users[:user].id, bool: 0)
        end
      end
      matches_users[:match] = match
      @matches.each do |m|
        if m[:user].id == matches_users[:user].id && m[:match].c_user_id == matches_users[:match].c_user_id
          matches_users.clear()
        end
      end
      if matches_users.present?
        matches_users[:c_user] = CUser.find(matches_users[:match].c_user_id)
        matches_users[:c_image] = Image.find_by(user_id: matches_users[:c_user].id, bool: 2)
        @matches << matches_users
      end
    end
  end

  def approve_match
    match = Match.find_by(approve_match_params)
    match_users = match.match_users
    match_user = nil
    match_users.each do |m_u|
      if m_u.user_id == current_user.id
        match_user = m_u
      end
    end
    match_user.step = 1
    match_user.save
    match.match_users.each do |match_user|
      if match_user.user_id != current_user.id
        if match_user.step == 1
          match.step = 1
          match.save
        end
      end
    end
    # match_userを持たないmatchを削除
    current_user_matches = Match.where(approve_match_c_user_params)
    current_user_matches.each do |unnecessary_match|
      if unnecessary_match.match_users == []
        unnecessary_match.destroy
      end
    end
    current_user_match_users = current_user.match_users
    current_user_match_users.each do |unnecessary_match_user|
      if unnecessary_match_user.match == nil
        match_id = unnecessary_match_user.match_id
        double_match_users = MatchUser.where(match_id: match_id)
        double_match_users.each do |double_match_user|
          double_match_user.destroy
        end
      end
    end
    redirect_to action: :match_approval
  end

  def destroy_match
    matches = Match.where(destroy_match_params)
    matches.each do |match|
      match.destroy
    end
    current_user_matches = Match.where(destroy_match_c_params)
    current_user_matches.each do |unnecessary_match|
      if unnecessary_match.match_users == []
        unnecessary_match.destroy
      end
    end
    current_user_match_users = current_user.match_users
    current_user_match_users.each do |unnecessary_match_user|
      if unnecessary_match_user.match == nil
        match_id = unnecessary_match_user.match_id
        double_match_users = MatchUser.where(match_id: match_id)
        double_match_users.each do |double_match_user|
          double_match_user.destroy
        end
      end
    end
    redirect_to action: :match_approval
  end

  def create_message
    @message = Message.new(create_message_params)
    if @message.save
      respond_to do |format|     
        format.json
      end
    end
  end

  def show_message
    @message = Message.new
    @items = []
    @messages = []
    matches = current_user.matches.where(c_user_id: params[:c_user_id])
    matches.each do |match|
      match.match_users.each do |match_user|
        if match_user.user_id != current_user.id
          user = User.find(match_user.user_id)
          image = Image.find_by(user_id: user.id, bool: 0)
          item = { user: user, image: image }
          @items << item
        end
      end
    end
    
    @c_user = CUser.find(params[:c_user_id])
    @c_image = Image.find_by(user_id: params[:c_user_id], bool: 2)
    # matches = Match.where(match_c_user_id: params[:c_user_id])
    messages = Message.where(bool: [0, 2], match_c_user_id: params[:c_user_id], user_id: current_user.id)
    messages.each do |message|
      @messages << message
    end

    respond_to do |format|
      format.json
    end
  end

  def show_user_message

app/views/mypage/li_render_list/_user_line_list.html.haml
%li.user_approval_list
  .leftBox
    .userBox
      .text
        お相手
      .image_link
        - if match[:image].present? && match[:image].image_url.present?
          = image_tag(match[:image].image_url, class: "image")
        - else 
          = image_tag('member_photo_noimage_thumb.png', class: "image")
      .nameBox
        = "#{match[:user].nickname}さん"
  .commentBox
    .top
      あなたにぴったりな所：
    .content
      - match[:match].match_users.each do |match_user|
        - if match_user.user_id != current_user.id
          = safe_join(match_user.content.split("\n"), tag(:br))
  .centerBox
    .c_userBox
      .text
        キューピット
      .image_link
        - if match[:c_image].present? && match[:c_image].image_url.present?
          = image_tag(match[:c_image].image_url, class: "image")
        - else
          = image_tag('member_photo_noimage_thumb.png', class: "image")
      .c_nameBox
        = "#{match[:c_user].nickname}"
  - match[:match].match_users.each do |match_user|
    - if match_user.user_id == current_user.id
      - if match_user.step == 0
        .approvalBox
          = form_with(model: @match, url: approve_match_mypage_index_path, local: true, class: "approve_form", id: "approve_form") do |form|
            = form.hidden_field :c_user_id, value: match[:c_user].id
            = form.hidden_field :user_id, value: match[:user].id
            = form.hidden_field :id, value: match[:match].id
            = form.submit "会いたい！", class: "approveBtn"
          = form_with(model: @match, url: destroy_match_mypage_index_path, local: true, class: "destroy_form", id: "destroy_form") do |form|
            -# idだけで破壊してあとはmodelのdependent: :destroyで良いと思う
            = form.hidden_field :c_user_id, value: match[:c_user].id
            = form.hidden_field :user_id, value: match[:user].id
            = form.hidden_field :id, value: match[:match].id
            = form.submit "無理...", class: "rejectBtn"
      - elsif match_user.step == 1
        .approvalBox
          .approval_textBox
            承認済み

      
    -# = form_with(model: @match, url: update_match_mypage_index_path, remote: true, class: "match_form", id: "approve_form_#{i + 1}") do |form|

    -# = form_with(model: @follow, url: create_follow_mypage_index_path, remote: true, class: "follow_form", id: "follow_form_#{i + 1}") do |form|

app/views/mypage/li_render_list/_user_list.html.haml
%li.listBox
  .imageBox
    .c_image_link{id: c_user.id}
      - if image.present?
        = image_tag image.image_url, class: "image"
      - else
        = image_tag "member_photo_noimage_thumb.png", class: "image"
  .bottomBox
    .nameBox
      = c_user.username
    .love_sustainableBox
      %i.fas.fa-heart
      = c_user.matches.where(step: 1).length
    .followerBox
      %i.fas.fa-user-graduate
      -# 生徒数なら@matches.length * 2、フォロワーならFollows.where(c_user: current_c_user) == @followerに.lengthだが、今回はfollowerにしようと思う。
      = c_user.follows.where(bool: 1).length
      人
    .specialtyBox
      .text
        %i.fas.fa-star
        得意分野
        %i.fas.fa-star
      - if c_user.speciality != nil
        = c_user.speciality.truncate(21)
    - follow_status = c_user.follows.find_by(user_id: current_user.id)
    - if follow_status.present?
      - if follow_status.bool == 0 then
        .followedBox{ id: c_user.id }
          = form_with(model: @follow, url: destroy_follow_mypage_index_path, remote: true, class: "follow_form", id: "follow_form_#{i + 1}") do |form|
            = form.hidden_field :c_user_id, value: c_user.id
            = form.hidden_field :user_id, value: current_user.id
            = form.submit "＋フォロー", class: "followedBtn"
      - elsif follow_status.bool == 1 then
        .followedBox{ id: c_user.id }
          = form_with(model: @follow, url: destroy_follow_mypage_index_path, remote: true, class: "follow_form", id: "follow_form_#{i + 1}") do |form|
            = form.hidden_field :c_user_id, value: c_user.id
            = form.hidden_field :user_id, value: current_user.id
            = form.submit "フォロバ", class: "followedBtn"
      - elsif follow_status.bool == 2 then
        .followBox{ id: c_user.id }
          = form_with(model: @follow, url: create_follow_mypage_index_path, remote: true, class: "follow_form", id: "follow_form_#{i + 1}") do |form|
            = form.hidden_field :c_user_id, value: c_user.id
            = form.hidden_field :user_id, value: current_user.id
            = form.submit "フォロバ", class: "followBtn"
    - else
      .followBox{ id: c_user.id }
        = form_with(model: @follow, url: create_follow_mypage_index_path, remote: true, class: "follow_form", id: "follow_form_#{i + 1}") do |form|
          = form.hidden_field :c_user_id, value: c_user.id
          = form.hidden_field :user_id, value: current_user.id
          = form.submit "＋フォロー", class: "followBtn"