config/routes.rb
Rails.application.routes.draw do
  devise_for :c_users, controllers:{
    sessions:       'c_users/sessions',
    passwords:      'c_users/passwords',
    registrations:  'c_users/registrations'
  }
  devise_for :users, controllers:{
    sessions:       'users/sessions',
    passwords:      'users/passwords',
    registrations:   'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root "informations#index"
  resources :mypage do
    collection do
      get "search"
    end
    collection do
      get "match"
    end
    collection do
      get "follow"
    end
    collection do
      get "find"
    end
    collection do
      get "community"
    end
    collection do
      post "create_follow"
    end 
    collection do
      post "destroy_follow"
    end
    collection do
      get "follower"
    end
    collection do
      get "match_approval"
    end
    collection do
      post "approve_match"
    end
    collection do
      post "destroy_match"
    end
    collection do
      get "show_message"
    end
    collection do
      post "create_message"
    end
    collection do
      get "show_user_message"
    end
    collection do
      get "skyway"
    end
    collection do
      get "create_skyway"
    end
    collection do
      get "show_c_detail"
    end
    collection do
      post "end_call"
    end
    collection do
      get "profile"
    end
    collection do
      post "update_profile"
    end
    collection do 
      post "add_main_image"
    end
    collection do
      post "add_sub_image"
    end
    collection do 
      get "delete_image"
    end
    collection do 
      get "qualification"
    end
  end
  resources :cmypage do
    collection do
      get "follower"
    end
    collection do
      get "search"
    end
    collection do
      get "find"
    end
    collection do
      get "community"
    end
    collection do
      get "user"
    end
    collection do
      get "match"
    end
    collection do
      get "follow"
    end
    collection do
      post "create_match"
    end
    collection do
      get "match_approvement"
    end
    collection do
      get "select_match"
    end
    collection do
      get "show_user"
    end
    collection do
      get "get_user_id"
    end
    collection do
      get "confirm_match"
    end
    collection do
      post "destroy_follow"
    end
    collection do
      post "create_follow"
    end
    collection do
      post "create_message"
    end
    collection do
      get "show_message"
    end
    collection do
      get "show_user_message"
    end
    collection do
      get "skyway"
    end
    collection do
      get "create_skyway"
    end
    collection do
      get "show_detail"
    end
    collection do
      post "end_call"
    end
    collection do
      get "profile"
    end
    collection do
      post "update_profile"
    end
    collection do 
      post "add_main_image"
    end
    collection do
      post "add_sub_image"
    end
    collection do 
      get "delete_image"
    end
    collection do
      get "qualification"
    end
  end
  namespace :api do
    resources :messages do
      collection do
        get "index_1"
      end
      collection do
        get "index_2"
      end
      collection do
        get "index_c"
      end
    end
  end
  # resources :messages
  resources :groups do
    resources :messages
  end
  resources :informations, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  before_action :authenticate_user!
  # before_action :configure_permitted_parameters, if: :devise_controller?
  
  def index
    
  end

  def find
    
  end

  def community
    
  end

  def follow
    @bool = "follow"
    @follow = Follow.new
    @my_image = Image.find_by(user_id: current_user.id, bool:0)
    c_users = []
    # フォロー中の人を取得
    user_follows = Follow.where(user_id: current_user.id, bool: [0, 1])
    user_follows.each do |user_follow|
      c_user_id = user_follow.c_user_id
      c_user = CUser.find(c_user_id)
      if c_users.include?(c_user)
      else
        c_users << c_user
      end
    end
    @items = []
    c_users.each do |c_user|
      image = Image.find_by(user_id: c_user.id, bool: 2)
      item = {image: image, c_user: c_user}
      @items << item
    end
  end

  def qualification
    down_age = params[:downage]
    up_age = params[:upage]
    sex = params[:sex]
    if sex == ""
      sex = [0, 1]
    end
    if down_age == ""
      down_age = "18"
    end
    if up_age == ""
      up_age = "100"
    end
    @element_per_page = 2
    @c_users = CUser.where(sex: sex, age: down_age..up_age).page(params[:page]).per(@element_per_page)
    @my_image = Image.find_by(user_id: current_user.id, bool:0)
    @follow = Follow.new
    @items = []
    @c_users.each do |c_user|
      image = Image.find_by(user_id: c_user.id, bool: 2)
      item = {image: image, c_user: c_user}
      @items << item
    end
  end

  def profile
    @my_image = Image.find_by(user_id: current_user.id, bool:0)
    @user = User.new
    @image = Image.new
    @user_info = User.find(current_user.id)
    all_images = Image.where(user_id: current_user.id)
    @main_image = all_images.find_by(bool: 0)
    images = all_images.where(bool: 1)
    @sub_images =[]
    images.each do |image|
      @sub_images << image
    end
  end

  def update_profile
    user = User.find(current_user.id)
    if user.update(update_profile_params)
      redirect_to search_mypage_index_path
    end
  end

  def add_main_image
    user_images = Image.where(user_id: current_user.id, bool: 0)
    user_image = user_images.first
    user_images.each do |image|
      if image != user_image
        image.destroy
      end
    end
    if user_image.present?
      if user_image.update!(add_image_params)
        redirect_to profile_mypage_index_path
      end
    else
      image = Image.new(add_image_params)
      # image = Image.new(image: add_image_params, bool: 0, user_id: current_user.id)
      image.bool = 0
      if image.save!
        redirect_to profile_mypage_index_path
      end
    end
  end

  def add_sub_image
    if Image.new_multiple_image(add_sub_image_params)
      redirect_to profile_mypage_index_path
    end
  end

  def delete_image
    @image_id = params[:id].to_i
    image = Image.find(@image_id)
    @bool = image.bool
    if image.destroy!
      respond_to do |format|
        format.json
      end
    end
  end

  def follower
    @bool = "follower"
    @follow = Follow.new
    c_users = []
    @my_image = Image.find_by(user_id: current_user.id, bool: 0)
    # フォロワーの取得
    user_followers = Follow.where(user_id: current_user.id, bool: [1, 2])
    user_followers.each do |user_follower|
      c_user_id = user_follower.c_user_id
      # @c_users << CUser.find(c_user_id)
      c_user = CUser.find(c_user_id)
      if c_users.include?(c_user)
      else
        c_users << c_user
      end
    end
    @items = []
    c_users.each do |c_user|
      image = Image.find_by(user_id: c_user.id, bool: 2)
      item = {image: image, c_user: c_user}
      @items << item
    end
  end

  def create_follow
    # binding.pry
    follow_backs = current_user.follows.where(follow_params).where(bool: [1, 2])
    follows = current_user.follows.where(follow_params).where(bool: 0)
    if follow_backs.present?
      follow_backs.each do |follow|
        follow.destroy
      end
      # @follow = current_user.follows.new(follow_bool_params)
      @follow = current_user.follows.new(follow_bool_params)
    else
      if follows.present?
        follows.each do |follow|
          follow.destroy
        end
      end
      @follow = current_user.follows.new(follow_zero_bool_params)
    end
    if @follow.save
      respond_to do |format|
        format.json
      end
      # redirect_to action: :search
    end
  end

  def destroy_follow
    @follows = Follow.where(destroy_follow_params)
    @follow = @follows.first()
    @follows.each do |follow|
      follow.destroy
      if follow.bool == 0
        follow.destroy
      elsif follow.bool == 1
        follow.destroy
        # binding.pry
        Follow.create(destroy_follow_two_bool_params)
        # binding.pry
      elsif follow.bool == 2
        # 相手フォロー時は何もしない
      else
        follow.destroy
      end
    end

    respond_to do |format|
      format.json
    end
  end

  def match
    @message = Message.new
    @my_image = Image.find_by(user_id: current_user.id, bool: 0)
    @matches_items = []
    matches = current_user.matches.where(step: 1)
    if matches.present?
      matches.each do |match|
        match_items = {}
        match_items[:c_user] = CUser.find(match.c_user_id)
        match.match_users.each do |match_user|
          if match_user.user_id != current_user.id
            match_items[:user] = User.find(match_user.user_id)
          end
        end
        @matches_items.each do |m_items|
          if m_items == match_items
            match_items.clear()
          end
        end
        if match_items.present?
          @matches_items << match_items
        end
      end
    end
    @matches_items.each do |matches_item|
      u_image = Image.find_by(user_id: matches_item[:user].id, bool: 0)
      c_image = Image.find_by(user_id: matches_item[:c_user].id, bool: 2)
      matches_item[:u_image] = u_image
      matches_item[:c_image] = c_image
    end
  end

  def match_approval
    @match = Match.new
    @my_image = Image.find_by(user_id: current_user.id, bool: 0)
    @matches = []
    matches = current_user.matches.where(step: 0)
    matches.each do |match|
      matches_users = {}
      match.match_users.each do |match_user|
        if match_user.user_id != current_user.id
          matches_users[:user] = User.find(match_user.user_id)
          matches_users[:image] = Image.find_by(user_id: matches_users[:user].id, bool: 0)
        end
      end
      matches_users[:match] = match
      @matches.each do |m|
        if m[:user].id == matches_users[:user].id && m[:match].c_user_id == matches_users[:match].c_user_id
          matches_users.clear()
        end
      end
      if matches_users.present?
        matches_users[:c_user] = CUser.find(matches_users[:match].c_user_id)
        matches_users[:c_image] = Image.find_by(user_id: matches_users[:c_user].id, bool: 2)
        @matches << matches_users
      end
    end
  end

  def approve_match
    match = Match.find_by(approve_match_params)
    match_users = match.match_users
    match_user = nil
    match_users.each do |m_u|
      if m_u.user_id == current_user.id
        match_user = m_u
      end
    end
    match_user.step = 1
    match_user.save
    match.match_users.each do |match_user|
      if match_user.user_id != current_user.id
        if match_user.step == 1
          match.step = 1
          match.save
        end
      end
    end
    # match_userを持たないmatchを削除
    current_user_matches = Match.where(approve_match_c_user_params)
    current_user_matches.each do |unnecessary_match|
      if unnecessary_match.match_users == []
        unnecessary_match.destroy
      end
    end
    current_user_match_users = current_user.match_users
    current_user_match_users.each do |unnecessary_match_user|
      if unnecessary_match_user.match == nil
        match_id = unnecessary_match_user.match_id
        double_match_users = MatchUser.where(match_id: match_id)
        double_match_users.each do |double_match_user|
          double_match_user.destroy
        end
      end
    end
    redirect_to action: :match_approval
  end

  def destroy_match
    matches = Match.where(destroy_match_params)
    matches.each do |match|
      match.destroy
    end
    current_user_matches = Match.where(destroy_match_c_params)
    current_user_matches.each do |unnecessary_match|
      if unnecessary_match.match_users == []
        unnecessary_match.destroy
      end
    end
    current_user_match_users = current_user.match_users
    current_user_match_users.each do |unnecessary_match_user|
      if unnecessary_match_user.match == nil
        match_id = unnecessary_match_user.match_id
        double_match_users = MatchUser.where(match_id: match_id)
        double_match_users.each do |double_match_user|
          double_match_user.destroy
        end
      end
    end
    redirect_to action: :match_approval
  end

  def create_message
    @message = Message.new(create_message_params)
    if @message.save
      respond_to do |format|     
        format.json
      end
    end
  end

  def show_message
    @message = Message.new
    @items = []
    @messages = []
    matches = current_user.matches.where(c_user_id: params[:c_user_id])
    matches.each do |match|
      match.match_users.each do |match_user|
        if match_user.user_id != current_user.id
          user = User.find(match_user.user_id)
          image = Image.find_by(user_id: user.id, bool: 0)
          item = { user: user, image: image }
          @items << item
        end
      end
    end
    
    @c_user = CUser.find(params[:c_user_id])
    @c_image = Image.find_by(user_id: params[:c_user_id], bool: 2)
    # matches = Match.where(match_c_user_id: params[:c_user_id])
    messages = Message.where(bool: [0, 2], match_c_user_id: params[:c_user_id], user_id: current_user.id)
    messages.each do |message|
      @messages << message
    end

    respond_to do |format|
      format.json
    end
  end

  def show_user_message

app/views/mypage/_header.html.haml
.header_logged_in
  .header_container
    .leftBox
      = link_to image_tag('cupido_logo.png', height: '60px', class: 'logo'), "#"
      .text
        恋愛・恋活マッチングサービス
    .rightBox
      = link_to image_tag('fukidashi.png', height: '40px', class: "fukidashi"), "#"
  .header_bottom

app/views/mypage/_main_follow_list.html.haml
.main-search-result
  .search-result-container
    %h2.subtitle
      - if @bool == "follow"
        フォロー中
      - else @bool == "follower"
        フォロワー
    %main.main_container
      - if @items.length != 0 then
        - for k in 0..3 do
          %ul.line_block
            - @items.each_with_index do |item, i|
              - if k == 0 then
                = render partial: "mypage/li_render_list/user_list", locals: { image: item[:image], c_user: item[:c_user], i: i, k: k }
                - if (i+1)%4 == 0 then
                  - break;
              - elsif k == 1 then
                - if i >= 4 && i <= 7 then
                  = render partial: "mypage/li_render_list/user_list", locals: { image: item[:image], c_user: item[:c_user], i: i, k: k }
                  - if (i+1)%4 == 0 then
                    - break;
              - elsif k == 2 then
                - if i >= 8 && i <= 11 then
                  = render partial: "mypage/li_render_list/user_list", locals: { image: item[:image], c_user: item[:c_user], i: i, k: k }
                  - if (i+1)%4 == 0 then
                    - break;
              - else
                - if i >= 12 && i <= 15 then
                  = render partial: "mypage/li_render_list/user_list", locals: { image: item[:image], c_user: item[:c_user], i: i, k: k }
                  - if (i+1)%4 == 0 then
                    - break;
      - elsif @items.length == 0 then
        .textBox
          データが見つかりませんでした。
    .c_user_information
    .search_qualification
    = form_with class: "authenticity_token_form"

app/views/mypage/_main_match.html.haml
.message_function_container
  .top_c_user_container
    %ul.c_user_listsBox
      - @matches_items.each do |m_items|
        %li.c_user_list
          .imageBox
            - if m_items[:c_image].present? && m_items[:c_image].image_url.present?
              = image_tag m_items[:c_image].image_url, class: 'match_c_user_imageBtn', id: m_items[:c_user].id
            - else
              = image_tag 'member_photo_noimage_thumb.png', class: 'match_c_user_imageBtn', id: m_items[:c_user].id
  .middle_user_container
    %ul.user_listsBox
      %li.all_user_list
        .imageBox
          .all_show_userBtn
            全て表示
  .messages_container
    .top_information
      キューピット
    .top_messages
      - if @messages.present?
        - @messages.each do |message|
          - if message.bool == 0
            = render partial: "/shared/my_message", local: {message: message}
          - if message.bool == 1
            = render partial: "/shared/other_message", local: {message: message}
    .bottom_message
      = form_with(model: @message, url: create_message_mypage_index_path, remote: true) do |form|
        = form.hidden_field :bool, value: 0, class: "message_bool"
        = form.hidden_field :user_id, value: current_user.id, class: "message_user_id"
        = form.hidden_field :match_c_user_id, value: 0, class: "message_match_c_user_id"

        -# = form_with(model: [@group, @message], local: true) do |form|
        .inputBox
          = form.text_area :content, placeholder: "メッセージを入力" , class: "match_textarea"
          = form.label :image, class: "image_label" do
            = form.file_field :image, class: "upload_image"
            %i.far.fa-image
          .submitView
            = button_tag type: 'submit', class: "message_submitBtn" do
              %i.far.fa-paper-plane
            

  

app/views/mypage/_main_result.html.haml
.main-search-result
  .search-result-container
    .main-searchBox
      .leftBox
        #u.searchBtn
          %i.fas.fa-search
          検索条件設定
      .centerBox
        - if @items.length != 0
          = @all_c_user_length
          人中
          = num = (@c_users.current_page - 1) * @element_per_page + 1
          &sim;
          = num - 1 + @items.length
          人表示中
        - else
          表示できるデータがありません
      .rightBox
        = link_to "#", class: "BlockBtn" do
          %i.fas.fa-th
    %main.main_container
      - if @items.length != 0 then
        - for k in 0..3 do
          %ul.line_block
            - @items.each_with_index do |item, i|
              - if k == 0 then
                = render partial: "mypage/li_render_list/user_list", locals: { image: item[:image], c_user: item[:c_user], i: i, k: k }
                - if (i+1)%4 == 0 then
                  - break;
              - elsif k == 1 then
                - if i >= 4 && i <= 7
                  = render partial: "mypage/li_render_list/user_list", locals: { image: item[:image], c_user: item[:c_user], i: i, k: k }
                  - if (i+1)%4 == 0 then
                    - break;
              - elsif k == 2 then
                - if i >= 8 && i <= 11
                  = render partial: "mypage/li_render_list/user_list", locals: { image: item[:image], c_user: item[:c_user], i: i, k: k }
                  - if (i+1)%4 == 0 then
                    - break;
              - else
                - if i >= 12 && i <= 15
                  = render partial: "mypage/li_render_list/user_list", locals: { image: item[:image], c_user: item[:c_user], i: i, k: k }
                  - if (i+1)%4 == 0 then
                    - break;
      = paginate @c_users
    .c_user_information
    .search_qualification
    = form_with class: "authenticity_token_form"


        

app/views/mypage/_nav_side.html.haml
.nav_side
  .side_header
    .mypage
      - if @my_image.present? && @my_image.image.present?
        = link_to image_tag(@my_image.image_url, width: "60px", class: "no_image"), profile_mypage_index_path, class: "no_image_link"
      - else
        = link_to image_tag('member_photo_noimage_thumb.png', width: "60px", class: "no_image"), profile_mypage_index_path, class: "no_image_link"
      = link_to profile_mypage_index_path, class: "center_linkBox" do
        %h2.name
          - if current_user.name.present?
            = current_user.name
          - else
            = current_user.username
        %h2.region
          東京
        %i.fas.fa-chevron-right
      .bottomBox
        %br/

  %ul.side_main
    %li.nav_list
      = link_to search_mypage_index_path, class: "nav_link", id: "user_nav_link_1" do
        キューピットを探す
        %i.fas.fa-chevron-right
    %li.nav_list
      = link_to match_mypage_index_path, class: "nav_link", id: "user_nav_link_2" do
        マッチング一覧
        %i.fas.fa-chevron-right
    %li.nav_list
      = link_to follow_mypage_index_path, class: "nav_link", id: "user_nav_link_3" do
        フォローリスト
        %i.fas.fa-chevron-right
  %ul.side_footer
    %li.footer_list
      = link_to "#", class: "nav_link" do
        %i.far.fa-question-circle
        ヘルプ
    %li.footer_list
      = link_to "#", class: "nav_link" do
        = image_tag 'beginner.png', width: '14px', class: 'beginner-image'
        はじめての方へ

    

app/views/mypage/_profile.html.haml
.profile_container
  .top_image_container
    .image_deleteBtn
      %i.fas.fa-trash-alt
      画像を削除
    .main_imageBtn
      .main_imageBox
        - if @main_image.present? && @main_image.image.present?
          = image_tag @main_image.image_url, class: 'top_image', id: "image#{@main_image.id}"
        - else
          = image_tag 'member_photo_noimage_thumb.png', class: 'top_image', id: "image0"
    .image_container
      - if @main_image.present?
        = image_tag @main_image.image_url, class: 'slide_image', id: "image#{@main_image.id}"
      - else
        .add_main_imageBtn
          = image_tag 'member_photo_noimage_thumb.png', class: 'slide_image', id: "image0"
          .text
            ＋メイン写真
      - if @sub_images.present?
        - @sub_images.each do |image|
          = image_tag image.image_url, class: 'slide_image', id: "image#{image.id}"
      .add_sub_imageBtn
        = image_tag 'member_photo_noimage_thumb.png', class: 'no_slide_image'
        .text
          ＋写真の追加
  .profile_elements
    %h2.subtitle
      プロフィール
    = form_with(model: @user, url: update_profile_mypage_index_path, local: true, class: "update_profile_form") do |form|
      .element#0
        facebookの名前(他人には公開されません)：
        .flexBox
          .text
            = @user_info.name
      .element#1
        ニックネーム：
        .flexBox
          = form.text_field :nickname, placeholder: "ニックネームを入力して下さい", value: @user_info.nickname, class: "update_text"
      .element#2
        ユーザーネーム：
        .flexBox
          = form.text_field :username, placeholder: "ユーザーネームを入力して下さい", value: @user_info.username, class: "update_text"
      .element#3
        プロフィール：
        .flexBox
          = form.text_area :profile, placeholder: "自己紹介文を入力して下さい", value: @user_info.profile, class: "update_textarea"
      = form.submit "プロフィールを更新する", class: "submitBtn"
  .add_container

app/views/mypage/community.html.haml
.wrapped
  = render "header"
  .main_contents
    = render "nav_side"
    = render "community_result"

app/views/mypage/find.html.haml
.wrapped
  = render "header"
  .main_contents
    = render "nav_side"
    = render "find_community"

app/views/mypage/follow.html.haml
.wrapped
  = render "header"
  .main_contents
    = render "nav_side"
    = render "main_follow_list"

app/views/mypage/follower.html.haml
.wrapped
  = render "header"
  .main_contents
    = render "nav_side"
    = render "main_follow_list"

app/views/mypage/match.html.haml
.wrapped
  = render "header"
  .main_contents
    = render "nav_side"
    = render "main_match"

app/views/mypage/match_approval.html.haml
.wrapped
  = render "header"
  .main_contents
    = render "nav_side"
    = render "match_approval"

app/views/mypage/search.html.haml
.wrapper
  = render "header"
  .main_contents
    = render "nav_side"
    = render "main_result"

app/views/mypage/skyway.html.erb
<!DOCTYPE html>
<html>
<head lang="ja">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>SkyWay JS SDK Tutorial</title>
    <%# <link rel="stylesheet" href="/app/assets/stylesheets/skyway.scss"> %>
</head>
<div class="pure-g">

    <!-- Video area -->
    <div class="pure-u-2-3" id="video-container">
        <video id="their-video" autoplay></video>
        <video id="my-video" muted="true" autoplay></video>
    </div>

    <!-- Steps -->
    <div class="pure-u-1-3">
        <h2>SkyWay Video Chat</h2>

        <p>Your id: <span id="my-id">...</span></p>
        <p>Share this id with others so they can call you.</p>
        <h3>Make a call</h3>
        <form id="make-call" class="pure-form">
            <input type="text" placeholder="Call user id..." id="callto-id">
            <button href="#" class="pure-button pure-button-success" type="submit">Call</button>
        </form>
        <form id="end-call" class="pure-form">
            <p>Currently in call with <span id="their-id">...</span></p>
            <button href="#" class="pure-button pure-button-success" type="submit">End Call</button>
        </form>
        <div class="skyway_code_textBox">
            <%= @skyway_code %>
        </div>
        <div class="c_user_id">
            <% if @c_user_id != 0 %>
                <%= @c_user_id %>
            <% end %>
        </div>
        <div class="user_id">
            <% if @user_id != 0 %>
                <%= @user_id %>
            <% end %>
        </div>
        <button class="make_a_call">
            電話チェック
        </button>
        <a href="/mypage/match" class="match_link">マッチング画面に戻る</a>
    </div>
</div>
</html>