config/routes.rb
Rails.application.routes.draw do
  devise_for :c_users, controllers:{
    sessions:       'c_users/sessions',
    passwords:      'c_users/passwords',
    registrations:  'c_users/registrations'
  }
  devise_for :users, controllers:{
    sessions:       'users/sessions',
    passwords:      'users/passwords',
    registrations:   'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root "informations#index"
  resources :mypage do
    collection do
      get "search"
    end
    collection do
      get "match"
    end
    collection do
      get "follow"
    end
    collection do
      get "find"
    end
    collection do
      get "community"
    end
    collection do
      post "create_follow"
    end 
    collection do
      post "destroy_follow"
    end
    collection do
      get "follower"
    end
    collection do
      get "match_approval"
    end
    collection do
      post "approve_match"
    end
    collection do
      post "destroy_match"
    end
    collection do
      get "show_message"
    end
    collection do
      post "create_message"
    end
    collection do
      get "show_user_message"
    end
    collection do
      get "skyway"
    end
    collection do
      get "create_skyway"
    end
    collection do
      get "show_c_detail"
    end
    collection do
      post "end_call"
    end
    collection do
      get "profile"
    end
    collection do
      post "update_profile"
    end
    collection do 
      post "add_main_image"
    end
    collection do
      post "add_sub_image"
    end
    collection do 
      get "delete_image"
    end
    collection do 
      get "qualification"
    end
  end
  resources :cmypage do
    collection do
      get "follower"
    end
    collection do
      get "search"
    end
    collection do
      get "find"
    end
    collection do
      get "community"
    end
    collection do
      get "user"
    end
    collection do
      get "match"
    end
    collection do
      get "follow"
    end
    collection do
      post "create_match"
    end
    collection do
      get "match_approvement"
    end
    collection do
      get "select_match"
    end
    collection do
      get "show_user"
    end
    collection do
      get "get_user_id"
    end
    collection do
      get "confirm_match"
    end
    collection do
      post "destroy_follow"
    end
    collection do
      post "create_follow"
    end
    collection do
      post "create_message"
    end
    collection do
      get "show_message"
    end
    collection do
      get "show_user_message"
    end
    collection do
      get "skyway"
    end
    collection do
      get "create_skyway"
    end
    collection do
      get "show_detail"
    end
    collection do
      post "end_call"
    end
    collection do
      get "profile"
    end
    collection do
      post "update_profile"
    end
    collection do 
      post "add_main_image"
    end
    collection do
      post "add_sub_image"
    end
    collection do 
      get "delete_image"
    end
    collection do
      get "qualification"
    end
  end
  namespace :api do
    resources :messages do
      collection do
        get "index_1"
      end
      collection do
        get "index_2"
      end
      collection do
        get "index_c"
      end
    end
  end
  # resources :messages
  resources :groups do
    resources :messages
  end
  resources :informations, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/cmypage_controller.rb
class CmypageController < ApplicationController
  before_action :authenticate_c_user!
  # before_action :configure_permitted_parameters, if: :devise_controller?
  
  def profile
    @my_image = Image.find_by(user_id: current_c_user.id, bool: 2)
    @c_user = CUser.new
    @image = Image.new
    @c_user_info = CUser.find(current_c_user.id)
    all_images = Image.where(user_id: current_c_user.id, bool: [2, 3])
    
    @main_image = all_images.find_by(bool: 2)
    images = all_images.where(bool: 3)
    @sub_images =[]
    images.each do |image|
      @sub_images << image
    end
  end

  def update_profile
    c_user = CUser.find(current_user.id)
    if c_user.update(update_profile_params)
      redirect_to search_cmypage_index_path
    end
  end

  def add_main_image
    c_user_images = Image.where(user_id: current_c_user.id, bool: 2)
    c_user_image = c_user_images.first
    c_user_images.each do |image|
      if image != c_user_image
        image.destroy
      end
    end
    if c_user_image.present?
      if c_user_image.update!(add_image_params)
        redirect_to profile_cmypage_index_path
      end
    else
      image = Image.new(add_image_params)
      # image = Image.new(image: add_image_params, bool: 0, user_id: current_user.id)
      image.bool = 2
      if image.save!
        redirect_to profile_cmypage_index_path
      end
    end
  end

  def add_sub_image
    if Image.c_new_multiple_image(add_sub_image_params)
      redirect_to profile_cmypage_index_path
    end
  end

  def delete_image
    @image_id = params[:id].to_i
    image = Image.find(@image_id)
    @bool = image.bool
    if image.destroy!
      respond_to do |format|
        format.json
      end
    end
  end

  def follow
    @follow = Follow.new
    @my_image = Image.find_by(user_id: current_c_user.id, bool: 2)
    user_ids = []
    follows = Follow.where(c_user_id: current_c_user.id, bool: [1, 2])
    follows.each do |follow|
      if user_ids.include?(follow.user_id)

      else
        user_ids << follow.user_id
      end
    end
    @items = []
    user_ids.each do |user_id|
      user = User.find(user_id)
      image = Image.find_by(user_id: user_id, bool: 0)
      item = { user: user, image: image }
      @items << item
    end
  end

  def follower
    @my_image = Image.find_by(user_id: current_c_user.id, bool: 2)
    @follow = Follow.new
    user_ids = []
    follows = Follow.where(c_user_id: current_c_user.id, bool: [0, 1])
    follows.each do |follow|
      if user_ids.include?(follow.user_id)

      else
        user_ids << follow.user_id
      end
    end
    @items = []
    user_ids.each do |user_id|
      user = User.find(user_id)
      image = Image.find_by(user_id: user_id, bool: 0)
      item = { user: user, image: image}
      @items << item
    end
  end

  def create_follow
    follow_backs = Follow.where(follow_params).where(bool: [0, 1])
    follows = Follow.where(follow_params).where(bool: 2)
    if follow_backs.present?
      follow_backs.each do |follow|
        follow.destroy
      end
      @follow = current_c_user.follows.new(follow_bool_params)
    else
      if follows.present?
        follows.each do |follow|
          follow.destroy
        end
      end
      @follow = current_c_user.follows.new(follow_two_bool_params)
    end
    if @follow.save
      respond_to do |format|
        format.json
      end
    end
  end

  def destroy_follow
    follows = current_c_user.follows.where(destroy_follow_params)
    @follow = follows.first()
    my_follows = follows.where(bool: 2)
    each_other_follows = follows.where(bool: [0, 1])
    if my_follows.present?
      my_follows.each do |follow|
        follow.destroy
      end
    else
      if each_other_follows.present?
        each_other_follows.each do |follow|
          follow.destroy
        end
      end
      @follow = current_c_user.follows.create(destroy_follow_zero_bool_params)
    end
    respond_to do |format|
      format.json
    end
  end

  def search
    @element_per_page = 2
    @my_image = Image.find_by(user_id: current_c_user.id, bool: 2)
    @follow = Follow.new
    original_users = []
    @all_user_length = User.all.length
    @users = User.page(params[:page]).per(@element_per_page)
    @users.each do |user|
      if original_users.include?(user)
      else
        original_users << user
      end
      if original_users.length >= 16
        break
      end
    end
    @items = []
    original_users.each do |user|
      image = Image.find_by(user_id: user.id, bool: 0)
      item = { user: user, image: image}
      @items << item
    end
  end

  def find
    
  end

  def community
    
  end

  def user
    
  end

  def match
    @message = Message.new
    @my_image = Image.find_by(user_id: current_c_user.id, bool: 2)
    matches = current_c_user.matches.where(step: 1)
    @items = []
    matches.each do |match|
      match.users.each do |user|
        item = {}
        if @items.present?
          @items.each_with_index do |already_item, i|
            if already_item[:user].id != user.id && @items.length != i + 1

            elsif already_item[:user].id == user.id
              break
            elsif already_item[:user].id != user.id && @items.length == i + 1
              item[:user] = user
            end
          end
        else
          item[:user] = user
        end
        if item != {}
          @items << item
        end
      end
    end
    @items.each do |item|
      user = item[:user]
      image = Image.find_by(user_id: user.id, bool: 0)
      item[:image] = image
    end
  end

  def show_message
    matches = []
    c_matches = current_c_user.matches.where(step: 1)
    user_id = params[:user_id].to_i
    user = User.find(user_id)
    image = Image.find_by(user_id: user.id, bool: 0)
    @item = { user: user, image:image }
    c_matches.each do |match|
      match.match_users.each do |match_user|
        if match_user.user_id == user_id      
          m = Match.find(match.id)
          matches << m
        end
      end
    end
    @others_items = []
    matches.each do |match|
      match.match_users.each do |match_user|
        if match_user.user_id != user_id
          u = User.find(match_user.user_id)
          image = Image.find_by(user_id: u.id, bool: 0)
          item = { user: u, image: image }
          if @others_items.include?(item)
          else
            @others_items << item
          end
        end
      end
    end
    @messages = []
    send_messages = Message.where(match_c_user_id: current_c_user.id, user_id: user_id, bool: 2)
    get_messages = Message.where(match_c_user_id: current_c_user.id, user_id: user_id, bool: 0)
    send_messages.each do |message|
      @messages << message
    end
    get_messages.each do |message|
      @messages.each_with_index do |array_message, i|
        if message.id < array_message.id
          @messages.insert(i, message)
          break
        elsif message.id > array_message.id && @messages.length == i + 1
          @messages.append(message)
        end
      end
    end
  end

  def show_user_message
    user_id = params[:user_id]
    @messages = Message.where(user_id: user_id, match_c_user_id: current_c_user.id, bool: [0, 2])
    user = User.find(user_id)
    image = Image.find_by(user_id: user_id, bool: 0)
    @item = {user: user, image: image}
  end

  def create_message
    @message = Message.create(create_message_params)
  end

  def select_match
    @my_image = Image.find_by(user_id: current_c_user.id, bool: 2)
  end

  def create_match
    user_id_1 = params[:user_id_1]
    user_id_2 = params[:user_id_2]
    match = current_c_user.matches.create(step: 0, memo: params[:memo])
    match_user_1 = match.match_users.create(user_id: user_id_1, content: params[:content1], step: 0)
    match_user_2 = match.match_users.create(user_id: user_id_2, content: params[:content2], step: 0)
    redirect_to action: :confirm_match
  end

  def match_approvement
    @match_users = []
    @my_image = Image.find_by(user_id: current_c_user.id, bool: 2)
    matches = Match.where(c_user_id: current_c_user.id, step: 0)
    matches.each do |match|
      items = {}
      match.match_users.each_with_index do |match_user, i|
        user_id = match_user.user_id
        step = match_user.step
        user = User.find(user_id)
        if i == 0
          items[:user1] = user
          items[:step1] = step
          items[:image1] = Image.find_by(user_id: user.id, bool: 0)
        elsif i == 1
          items[:user2] = user
          items[:step2] = step
          items[:image2] = Image.find_by(user_id: user.id, bool: 0)
        end
      end
      memo = match.memo
      items[:memo] = memo

      if @match_users.include?(items)
      elsif items[:user1].present?
        @match_users << items
      end
    end
  end

  def confirm_match
    
  end

  def show_user
    @create_id = params[:create_id].to_s
    @items = []
    user_ids = []
    # @follows = current_c_user.follows.where(bool: 1)
    follows = current_c_user.follows.where(bool: 1).limit(32)
    i = 0
    follows.each do |follow|
      i += 1
      if i == 17
        break
      end
      if user_ids.include?(follow.user_id)
      else
        user_ids << follow.user_id
      end
    end
    user_ids.each do |user_id|
      item = {}
      item[:user] = User.find(user_id)
      item[:image] = Image.find_by(user_id: user_id, bool: 0)
      @items << item
    end
  end

  def get_user_id
    user_id = params[:user_id].to_i
    @select_id = params[:select_id].to_i
    @user = User.find(user_id)
    @image = Image.find_by(user_id: user_id, bool: 0)
  end

  def show_detail
    user_id = params[:user_id]
    @user = User.find(user_id)
    @image = Image.find_by(user_id: user_id, bool: 0)
    @sub_images = Image.where(user_id: user_id, bool: 1)
    @student_length = current_c_user.follows.where(bool: 1).length
    @follower_length = current_c_user.follows.where(bool: [0, 1]).length
  end

  def skyway

app/views/cmypage/_follower.html.haml
.c_follower_container
  .search-result-container
    %h2.subtitle
      フォロワー
    %main.main_container
      - if @items.length != 0 then
        - for k in 0..3 do
          %ul.line_block
            - @items.each_with_index do |item, i|
              - if k == 0 then
                = render partial: "cmypage/li_render_list/c_user_list", locals: { image: item[:image], user: item[:user], i: i, k: k}
                - if (i+1)%4 == 0 then
                  - break
              - elsif k == 1 then
                - if i >= 4 && i <= 7
                  = render partial: "cmypage/li_render_list/c_user_list", locals:  { image: item[:image], user: item[:user], i: i, k: k}
                  - if (i+1)%4 == 0 then
                    - break
              - elsif k == 2 then
                - if i >= 8 && i <= 11
                  = render partial: "cmypage/li_render_list/c_user_list", locals:  { image: item[:image], user: item[:user], i: i, k: k}
                  - if (i+1)%4 == 0 then
                    - break
              - elsif k == 3 then
                - if i >= 12 && i <= 15
                  = render partial: "cmypage/li_render_list/c_user_list", locals:  { image: item[:image], user: item[:user], i: i, k: k}
                  - if (i+1)%4 == 0 then
                    - break
      - elsif @items.length == 0 then
        .textBox
          データが見つかりませんでした。
    .user_information
      

app/views/cmypage/_header.html.haml
.header_logged_in
  .header_container
    .leftBox
      = link_to image_tag('cupido_logo.png', height: '60px', class: 'logo'), "#"
      .text
        恋愛・恋活マッチングサービス
    .rightBox
      = link_to image_tag('fukidashi.png', height: '40px', class: "fukidashi"), "#"
  .header_bottom

app/views/cmypage/_match.html.haml
.message_function_container
  .top_user_container
    %ul.user_listsBox
      - @items.each do |item|
        -# =item
        %li.user_list
          .imageBox
            - if item[:image] != nil
              = image_tag item[:image].image_url, class: 'match_user_imageBtn_up', id: item[:user].id
            - else
              = image_tag 'member_photo_noimage_thumb.png', class: 'match_user_imageBtn_up', id: item[:user].id
      
      
  .middle_user_container
    %ul.user_listsBox
    -#   %li.user_list
    -#     .imageBox
    -#       = image_tag 'member_photo_noimage_thumb.png', class: 'match_user_imageBtn_down', id: ""
  .messages_container
    .top_information
      ユーザー
      
    .top_messages
      
    .bottom_message
      = form_with(model: @message, url: create_message_cmypage_index_path, remote: true) do |form|
        -# = form_with(model: [@group, @message], local: true) do |form|
        = form.hidden_field :bool, value: 2, class: "new_message_bool"
        = form.hidden_field :match_c_user_id, value: current_c_user.id
        = form.hidden_field :user_id, value: 0, class: "new_message_user_id"
        .inputBox
          = form.text_area :content, placeholder: "メッセージを入力" , class: "match_textarea"
          = form.label :image, class: "image_label" do
            = form.file_field :image, class: "upload_image"
            %i.far.fa-image
          .submitView
            = button_tag type: 'submit', class: "c_message_submitBtn" do
              %i.far.fa-paper-plane
            

  

app/views/cmypage/_match_approvement.html.haml
.main_match_approval_container
  .match_approval_header
    %h2.title
      マッチング申請一覧
  %ul.match_approval_listsBox
    - if @match_users.length == 0 then
      .textBox
        現在マッチング申請はありません
    - elsif @match_users.length != 0 then
      - @match_users.each do |match_user|
        = render partial: "cmypage/li_render_list/c_user_line_list", locals: {match_user: match_user}

app/views/cmypage/_nav_side.html.haml
.nav_side
  .side_header
    .mypage
      - if @my_image.present? && @my_image.image.present?
        = link_to image_tag(@my_image.image_url, width: "60px", class: "no_image"), profile_cmypage_index_path, class: "no_image_link"
      - else
        = link_to image_tag('member_photo_noimage_thumb.png', width: "60px", class: "no_image"), profile_cmypage_index_path, class: "no_image_link"
      = link_to profile_cmypage_index_path, class: "center_linkBox" do
        %h2.name
          = current_c_user.username
        %h2.region
          東京
        %i.fas.fa-chevron-right
      .bottomBox
        %br/
  %ul.side_main
    %li.nav_list
      = link_to search_cmypage_index_path, class: "nav_link", id: "c_user_nav_link_1" do
        ユーザーを探す
        %i.fas.fa-chevron-right
    %li.nav_list
      = link_to match_cmypage_index_path, class: "nav_link", id: "c_user_nav_link_2" do
        マッチング一覧
        %i.fas.fa-chevron-right
    %li.nav_list
      = link_to follower_cmypage_index_path, class: "nav_link", id: "c_user_nav_link_3" do
        フォロワーリスト
        %i.fas.fa-chevron-right

  %ul.side_footer
    %li.footer_list
      = link_to "#", class: "nav_link" do
        %i.far.fa-question-circle
        ヘルプ
    %li.footer_list
      = link_to "#", class: "nav_link" do
        = image_tag 'beginner.png', width: '14px', class: 'beginner-image'
        はじめての方へ

    

app/views/cmypage/_profile.html.haml
.profile_container
  .top_image_container
    .image_deleteBtn
      %i.fas.fa-trash-alt
      画像を削除
    .main_imageBtn
      .main_imageBox
        - if @main_image.present? && @main_image.image.present?
          = image_tag @main_image.image_url, class: 'top_image', id: "image#{@main_image.id}"
        - else
          = image_tag 'member_photo_noimage_thumb.png', class: 'top_image', id: "image0"
    .image_container
      - if @main_image.present?
        = image_tag @main_image.image_url, class: 'slide_image', id: "image#{@main_image.id}"
      - else
        #c.add_main_imageBtn
          = image_tag 'member_photo_noimage_thumb.png', class: 'slide_image', id: "image0"
          .text
            ＋メイン写真
      - if @sub_images.present?
        - @sub_images.each do |image|
          = image_tag image.image_url, class: 'slide_image', id: "image#{image.id}"
      #c.add_sub_imageBtn
        = image_tag 'member_photo_noimage_thumb.png', class: 'no_slide_image'
        .text
          ＋写真の追加
  .profile_elements
    %h2.subtitle
      プロフィール
    = form_with(model: @c_user, url: update_profile_cmypage_index_path, local: true, class: "update_profile_form") do |form|
      .element#1
        ニックネーム：
        .flexBox
          = form.text_field :nickname, placeholder: "ニックネームを入力して下さい", value: @c_user_info.nickname, class: "update_text"
      .element#2
        ユーザーネーム：
        .flexBox
          = form.text_field :username, placeholder: "ユーザーネームを入力して下さい", value: @c_user_info.username, class: "update_text"
      .element#4
        性別：
        .flexBox
          = form.select :sex, {男: 0, 女: 1}, include_blank: '性別', selected: @c_user_info.sex, class: "update_text"
      .element#5
        年齢：
        .flexBox
          = form.select :age, 18..100, include_blank: '年齢', selected: @c_user_info.age, class: "update_text"
      .element#6
        ひとこと
        .flexBox
          = form.text_field :speciality, placeholder: 'こんなことを教えるのが得意とかあればどうぞ！', value: @c_user_info.speciality, class: "update_text"
      .element#3
        プロフィール：
        .flexBox
          = form.text_area :profile, placeholder: "自己紹介文を入力して下さい", value: @c_user_info.profile, class: "update_textarea"
      = form.submit "プロフィールを更新する", class: "submitBtn"
  .add_container

app/views/cmypage/_select_match.html.haml
.create_match_container
  .headerBox
    %h1.title
      マッチング作成
  = form_with(model: @match, url: create_match_cmypage_index_path, local: true, class: "create_match_form") do |form|
    .matching_container
      .flexBox
        .leftBox
          %h2.subtitle
            会員様１
            .number_id_1
              会員id: 
          .imageBox
            .image_link_create#imageBox_create_1
              = image_tag "member_photo_noimage_thumb.png", class: "image"
          .name#1
            名前１
          = form.text_area :content1, placeholder: "会員様１へ送る会員様２の紹介メッセージ（200字以内）", class: "introduce_area"

        .centerBox
          = image_tag 'love_arrow.png', class: 'image'
        .rightBox
          %h2.subtitle
            会員様２
            .number_id_2
              会員id: 
          .imageBox
            .image_link_create#imageBox_create_2
              = image_tag "member_photo_noimage_thumb.png", class: "image"
          .name#2
            名前２
          = form.text_area :content2, placeholder: "会員様２へ送る会員様１の紹介メッセージ（200字以内）", class: "introduce_area"
      .bottomBox
        %h3.memo_title
          自分用メモ：
        = form.text_area :memo, placeholder: "あとで見返せる自分用のメモ (会員様からは見えません)", class: "memo"
        .confirmBox
          %h2.subtitle
            ⚠️マッチング作成前に
          .text
            ・記入漏れはありませんか？
            %br/
            ・会員様の２つの紹介文記入欄は会員様１の下に会員様２の、会員様２の下に会員様１のがあります。お間違えないように今一度確認をよろしくお願いします。
            %br/
            %br/
            以上、誤りがないことを確認して、
        = form.submit "マッチング申請する", class: "submitBtn", id: "create_matchBtn"
  .show_select_containerBox

app/views/cmypage/follow.html.haml
.wrapped
  = render "header"
  .main_contents
    = render "nav_side"
    = render "follow"

app/views/cmypage/match.html.haml
.wrapped
  = render "header"
  .main_contents
    = render "nav_side"
    = render "match"

app/views/cmypage/match_approvement.html.haml
.wrapped
  = render "header"
  .main_contents
    = render "nav_side"
    = render "match_approvement"

app/views/cmypage/profile.html.haml
.wrapped
  = render "header"
  .main_contents
    = render "nav_side"
    = render "profile"

app/views/cmypage/qualification.html.haml
.wrapped
  = render "header"
  .main_contents
    = render "nav_side"
    = render "search"

app/views/cmypage/search.html.haml
.wrapped
  = render "header"
  .main_contents
    = render "nav_side"
    = render "search"

app/views/cmypage/skyway.html.erb
<!DOCTYPE html>
<html>
<head lang="ja">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>SkyWay JS SDK Tutorial</title>
    <%# <link rel="stylesheet" href="/app/assets/stylesheets/skyway.scss"> %>
</head>
<div class="pure-g">

    <!-- Video area -->
    <div class="pure-u-2-3" id="video-container">
        <video id="their-video" autoplay></video>
        <video id="my-video" muted="true" autoplay></video>
    </div>

    <!-- Steps -->
    <div class="pure-u-1-3">
        <h2>SkyWay Video Chat</h2>

        <p>Your id: <span id="my-id">...</span></p>
        <p>Share this id with others so they can call you.</p>
        <h3>Make a call</h3>
        <form id="c_make-call" class="pure-form">
            <input type="text" placeholder="Call user id..." id="callto-id">
            <button href="#" class="pure-button pure-button-success" type="submit">Call</button>
        </form>
        <form id="c_end-call" class="pure-form">
            <p>Currently in call with <span id="their-id">...</span></p>
            <button href="#" class="pure-button pure-button-success" type="submit">End Call</button>
        </form>
        <div class="skyway_code_textBox">
            <%= @skyway_code %>
        </div>
        <div class="user_id">
            <%= @user_id %>
        </div>
        <button class="make_a_call">
            電話チェック
        </button>
        <a href="/cmypage/match" class="match_link">マッチング画面に戻る</a>
    </div>
</div>
<%# <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script> %>
<%# <script type="text/javascript" src="https://cdn.webrtc.ecl.ntt.com/skyway-latest.js"></script> %>
<%# <script type="text/javascript" src="/app/assets/javascripts/skyway/script.js"></script> %>
</html>